import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { ClerkProvider, SignedIn, SignedOut, RedirectToSignIn } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/providers/theme-provider"
import { SpotifyProvider } from '@/components/providers/spotify-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import { SpotifyPlayer } from '@/components/player';

const inter = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Harmony Sage',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className}>
          <ThemeProvider
            defaultTheme='dark'
            attribute='class'
            enableSystem={false}
            storageKey='harmony-sage-theme'
          >
            <SpotifyProvider>
              <QueryProvider>

                {children}
                <SpotifyPlayer />
              </QueryProvider>
            </SpotifyProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
